Add core files
Estete9/hello-microverse pull request #2
Opened 2023-06-01 22:30 UTC by Estete9

Add README.md, index.html, style.css, test.md, and gitignore which includes the test.md file and node_modules

2023-06-02 00:23 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @Estete9 , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

- [ ] kindly edit your  Pull Request title to be more descript ,example "Hello Microverse Milestone",Pull Request should have a descriptive title telling you what changes are inside.
- [ ] Kindly edit your PR sumary to be more desriptive  your a Pull Request should have a summary describing introduced changes in more detail.
example of a decriptive PR sumarry 
![Prefesssional PR](https://github.com/Estete9/hello-microverse/assets/92458236/7cdf89ea-a50f-4234-b160-9dba3ea1ecea)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 00:23 UTC, ademibowale commented on README.md
> +- FAQ
- [ ] Kindly remove all paceholder texts from your readme make your reeadme file look professional as the placeholder text is thir for a guildelines on how to make each section

2023-06-02 00:23 UTC, ademibowale commented on README.md
> +
- [ ] i would kindly suggest you to remove the `live demo link`, becouse the project is not yet deploy ,you can just replace with `coming soon `for now untill its deploy,

2023-06-02 00:23 UTC, ademibowale commented on README.md
> +- LinkedIn: [Esteban Palacios](https://www.linkedin.com/in/esteban-palacios-5030a772/)
- [ ] i would sugest you to include your twtter handle this also way recrulter connect a developer in future.

2023-06-02 00:23 UTC, ademibowale commented on README.md
> +**Hello Microverse** is a starting project to test linters and core files like gitignore with GitHub...
- [ ] i can see that you have missed some important sections on your readme e.g (GET STARTED SECTION e.t.c) ,according to requirement its only the FAQ is optional all section must be included except the FAQ is optional  see the  screenshot below to compare .
- [ ] 
![PREFESSIONAL Readme](https://github.com/Estete9/hello-microverse/assets/92458236/9e3a971b-2011-40c0-b39d-ca6710038831)

- [ ]

2023-06-02 13:12 UTC, Estete9 commented on README.md
> +**Hello Microverse** is a starting project to test linters and core files like gitignore with GitHub...
Thank you for the feedback, in this case, what should I do if some of these I don't know how to fill? (that's the reason I removed them)
Specifically the Setup, Prerequisites, Install, Usage, Run Tests, and some parts of the Built with.

2023-06-03 17:12 UTC, Estete9 commented
Updated the README file, and the PR title and description

2023-06-03 17:12 UTC, merged

2023-06-03 17:34 UTC, rica213 reviewed
# 🟢 STATUS: APPROVED
Hi Esteban
My name is Larissa. I am your code reviewer 🥰

I see you have completed all the required changes requested by the previous reviewer 😍  Thank you for that ❤️  Now your documentation is looking professional 📄 You did a great job 💯 👍🏽 
Your project is complete!  Now let's merge it 🛸 🛸 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/ely3apij36BJhoZ234/giphy-downsized-medium.gif"/>

## Highlights

- [ ] No Linters errors ✔️ 
- [ ] Descriptive PR title and summary ✔️
- [ ] Descriptive commit messages 
- [ ] Correct Github flow ✔️ 
- [ ] Professional Documentation ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 17:34 UTC, rica213 commented on README.md
> +  </ul>
- [ ] [OPTIONAL] Please only mention something related to your project. 🙏🏽 Documentation serves as a guide for our users so it should not contain false information. It would create confusion 💔 
For example, during this milestone, we do not use **Postgresql** so we should not mention that. 🤗